### ISSUE TITLE
Unable to use the package

### ISSUE THREAD

**Issue by shwetank2174** [taylorhakes/python-redis-cache#1]
Could you please help me with an example of how I can use it?
I am unable to understand how to deploy this package.

**Comment by taylorhakes** [comment]
@shwetank2174 Could you provide more details about what issue you are having? What do you mean about `deploy this package`? Do you mean install? Did you read the [README](https://github.com/taylorhakes/python-redis-cache#how-to-use) already?

**Comment by taylorhakes** [comment]
@shwetank2174 Closing this issue. Please feel free to comment with more details I will be happy to reopen
