### ISSUE TITLE
If  I want to pause the caching (while debugging) what is the best way to accomplish that?

### ISSUE THREAD

**Issue by apurvak** [taylorhakes/python-redis-cache#13]

**Comment by taylorhakes** [comment]
There is currently no way to do that. I think this feature does make sense though. Do you have time to create a PR?

**Comment by lowercase00** [comment]
@taylorhakes  thoughts on the API?
Maybe adding a `debug` flag to the main `RedisCache` class. `if debug: pass` on the decorator?
