### ISSUE TITLE
Use __qualname__ instead of __name__ for the namespace

### ISSUE THREAD

**Issue by rafammpp** [taylorhakes/python-redis-cache#14]
If you have two classes with the same method name inside a module and cache both, the keys will be the same because  `__name__` only returns the name of the method. But `__qualname__` returns the name of the class and the name of the method.
So, can you use that instead?
In any case, thanks for your work!

**Comment by taylorhakes** [comment]
Thanks for flagging this bug. This is going to be a breaking change, so will require a major version change. Do you have time to put up a PR?

**Comment by rafammpp** [comment]
@taylorhakes Done! https://github.com/taylorhakes/python-redis-cache/pull/15
