### ISSUE TITLE
Ability to ignore provided function results

### ISSUE THREAD

**Issue by sashaaero** [taylorhakes/python-redis-cache#16]
Hello. Simple case - your function fetches some data from remote resource. This resource can return some error, for example "Service unavailable". So response from my backend is similar. 
Surely I don't want to cache this result for any time.

I think something like
```
@cache.cache(..., ignore_results=(None))
def func(...):
    ...
    if response.status_code == 503:
        return None
    ...
```

So if you call it again with same arguments it won't use this cache.

If you okay with this idea I can try to implement this and make a PR.

**Comment by taylorhakes** [comment]
Sorry for the delay. I like this idea. I wonder if an exception would be better?  I am worried about people wanting to support errors and None as a real value?

I guess exceptions already don’t cache the already. So i guess your suggestion might be best. Do you have time to create a PR?
