### ISSUE TITLE
Pass caching when redis server goes down during execution

### ISSUE THREAD

**Issue by DavidOsparks** [taylorhakes/python-redis-cache#21]
It seems that the CacheDecorator does not have a mechanism to stop caching and revert back to directly running the function to retrieve values when the redis server goes down. Maybe add something like this?
```
        @wraps(fn)
        def inner(*args, **kwargs):
            nonlocal self
            key = self.get_key(args, kwargs)

            try:
                result = self.client.get(key)
            except (RedisError, ConnectionError):    # Maybe need more like BusyLoadingError, ...
                result = fn(*args, **kwargs)
                return result

            if not result:
                result = fn(*args, **kwargs)
                result_serialized = self.serializer(result)
                get_cache_lua_fn(self.client)(keys=[key, self.keys_key], args=[result_serialized, self.ttl, self.limit])
            else:
                result = self.deserializer(result)
            return result
```
Perhaps similar ignore mechanisms could be added to invalidate() and invalidate_all() so that the program can continue running when redis server goes down.

**Comment by taylorhakes** [comment]
Good point. I think some people may want this behavior and some may not.For instance the query could be very expensive and it could cause more issues if all the requests start hitting the slow path. I think it needs to be a configuration option. Happy to accept a PR that adds a fallback, but it needs to be enable via a flag.

**Comment by DavidOsparks** [comment]
Although I find it strange that a system would crash due to a cache failure, there may be still a function which is so expensive that they would rather let the system crash than execute it a second time (although this should be considered poor system design. In this situation there should be another permanent storage besides the cache).

I thought of a solution where users can pass a callable object for error handling. This way, they can write their own alternative solution for cache failure without causing the entire system to crash. If the user does not pass this error handling function, the original function will be called. Maybe like this (not very sure):

```
class CacheDecorator:
    def __init__(self, redis_client, prefix="rc", serializer=compact_dump, deserializer=loads, key_serializer=None, ttl=0, limit=0, namespace=None, error_handling_func=None):
    # ...
        self.error_handling_func = error_handling_func.     # add this
    # ...
    
        @wraps(fn)
        def inner(*args, **kwargs):
            nonlocal self
            key = self.get_key(args, kwargs)

            try:
                result = self.client.get(key)
            except (RedisError, ConnectionError):    # Maybe need more like BusyLoadingError, ...
                if self.error_handling_func:                  # add this
                    result = self.error_handling_func(*args, **kwargs)
                else:
                    result = fn(*args, **kwargs)
                return result

            if not result:
                result = fn(*args, **kwargs)
```

**Comment by taylorhakes** [comment]
> although this should be considered poor system design. In this situation there should be another permanent storage besides the cache

The cache is necessary because people don't want to use the other permanent storage. The same could be said of having your cache fail. Why not just have a backup cache. I don't agree necessarily that it's bad system design (it could be). Cache can be on a part of system that is not high priority and they don't want a failure in cache to affect other systems by making a ton of expensive queries.

That being said. I would be happy to accept a PR with the functionality you described above. Please make sure to add tests as well
