### ISSUE TITLE
Support for jsonable_encoder for pydantic responses

### ISSUE THREAD

**Issue by sharath29** [taylorhakes/python-redis-cache#32]
For pydantic classes the cache gives "the object is not JSON serializable" error response. This would need jsonable_encoder to be set as the encoder recommended by [fastapi](https://fastapi.tiangolo.com/tutorial/encoder/). 

since jsonable_encoder return dict instead of string we would need to handle this case

```python
        if isinstance(serialized_data, dict):
            serialized_data = compact_dump(serialized_data).encode('utf-8')
```

**Comment by taylorhakes** [comment]
Thanks for the report. Unfortunately this isn’t an easy fix if I understand the issue correctly.

The pydantic classes need a serializer and a deserializable (to return them back to their original classes from string cache). 

You can always write your own custom serializer/deserializer. You just need to create a custom function that seeializes to a dict and then calls dump. Then you can pass that new function to this library. Remember you also have to implement a deserializer as well.

Another option is using the pickle option, but make sure you understand the security risks.

Does that not work in this case?

**Comment by sharath29** [comment]
> Thanks for the report. Unfortunately this isn’t an easy fix if I understand the issue correctly.
> 
> The pydantic classes need a serializer and a deserializable (to return them back to their original classes from string cache).
> 
> You can always write your own custom serializer/deserializer. You just need to create a custom function that seeializes to a dict and then calls dump. Then you can pass that new function to this library. Remember you also have to implement a deserializer as well.
> 
> Another option is using the pickle option, but make sure you understand the security risks.
> 
> Does that not work in this case?

Makes sense, I have started to use the pickle approach. Thanks for maintaining this library!
