### ISSUE TITLE
Option to disable the cache & Default TTL

### ISSUE THREAD

**Issue by AviSarmani** [taylorhakes/python-redis-cache#34]
Hi,
Thanks for the repo, great work!
I want to suggest a couple of features
1. Add the option to disable the cache
I need to have the ability to disable the cache based on an env. variable(ie. lower environments or troubleshooting) without changing the code and preferably without creating my own wrapper
Maybe some sort of an "active" flag when instantiating the cache so that if it's inactive just return the wrapped function itself?
Flaks-caching(which I'm trying to migrate from) does this by setting if it helps
cache_config = {
        "CACHE_TYPE": "null",
    }

2. Add the ability for a default TTL when instantiating the cache.
For now my code in all cache parts(a lot) looks like this and it looks cumbersome
`@cache.cache(ttl=int(os.getenv("CACHE_TTL", "3600"))`
It would be cleaner to set a default when creating the object.

Thanks!

**Comment by taylorhakes** [comment]
Hey @AviSarmani. Thanks for reporting those feature requests. They both seem very reasonable.

I would be happy to merge a PR if you implemented those features and added some tests. Would you be able to do that?

**Comment by AviSarmani** [comment]
Hi @taylorhakes,
Would be happy to.
Please take a look at https://github.com/taylorhakes/python-redis-cache/pull/35 as I haven't contributed to an open source project before.
If it looks good, I'll take a look at point 2.
