### ISSUE TITLE
How to use cache decorator inside class method

### ISSUE THREAD

**Issue by jashwant** [taylorhakes/python-redis-cache#40]
How can we use cache decorator inside a class without providing a custom serializer for every class?
  
I have following class.
  
````python 
class Myclass:
  def my_def2(self, value):
    return value + 2
    
  @cache.cache()
  def my_def(self, value):
     value += 5
     return self.mydef2(value)
````     
This throws TypeError as json serializer doesn't recognize the type of self argument.

I am dealing with it like this.
     
````python
def compact_dump(value):
  self_arg = value.get('self')
  # Don't have access to func here, so can't check func.__qualname__ != func.__name__. 
  # May be wrap @cache inside another decorator and check func.__qualname__ != func.__name__ there.
  # May be add condition self_arg is it not int, float, tuple, dict etc as they are inherited from object class
  if self_arg is not None and isinstance(self_arg, object):
    value.pop('self')
  return dumps(value, separators=(",", ":"), sort_keys=True)
         
cache = RedisCache(redis_client=client, serializer=compact_dump)
````

But this looks hackish. Is there a better/recommeded way to deal with it?

I just want to throw decorator @cache without worrying about the method type.

**Comment by mrisher** [comment]
I'm hitting the same issue; I was able to work around it by overriding `key_serializer` with a custom function, but that seems hackish also. I wonder if we want `__repr__` for the module name?

**Comment by taylorhakes** [comment]
Thanks for the bug report guys. If you all can come up with a good way to handle this that would be great (propose it in this thread before writing code). It's definitely hard to deal with this generically. It seems like the class instance needs to be serializable for this to work correctly. If `self` doesn't matter, it should probably be a static function instead.

**Comment by taylorhakes** [comment]
@jashwant In the example you showed below. Both methods should be static (`@staticmethod``). Nothing relies on `self`.

```python
class Myclass:
  def my_def2(self, value):
    return value + 2
    
  @cache.cache(ignore_kwargs=['self'])
  def my_def(self, value):
     value += 5
     return self.mydef2(value)
```

If something uses `self`, it likely needs to be serialized

**Comment by mrisher** [comment]
Good point, in my case the methods were static as well so I only needed a cache key. 
Maybe the solution is documentation -- throwing a more specialized error and saying that if it's a class method, you need to either override the `__hash__()` method for the class (that should work, right?) or provide a custom `key_serializer` method?

**Comment by taylorhakes** [comment]
Sounds good. I should definitely update the documentation

> throwing a more specialized error and saying that if it's a class method, you need to either override the __hash__() method for the class (that should work, right?

Yes, that could be 1 way to do it. The code is currently doesn't handle __hash__ today, but we could implement a custom JSON serializer to do user __hash__ for objects.

**Comment by taylorhakes** [comment]
I updated the docs here. Please let me know if I should close this issue or not.

https://github.com/taylorhakes/python-redis-cache?tab=readme-ov-file#instanceclass-methods

**Comment by mrisher** [comment]
Beautiful, thank you for the documentation @taylorhakes ! For me this is closed.

**Comment by jashwant** [comment]
@taylorhakes 

Thanks for the documentation update.
Instead of using another static method, I am creating inner method.

class Myclass:
  def my_def2(self, value):
    return value + 2
    
  def my_def(self, value):  
    @cache.cache()
    def inner(value):
       value += 5
       return self.mydef2(value)
     return inner(value)
