### ISSUE TITLE
Decorating async functions?

### ISSUE THREAD

**Issue by mrisher** [taylorhakes/python-redis-cache#41]
Hi:
This may be simple, but I can't find in the docs or the code: How do I cache the results of an async function? I'm getting an error that a coroutine isn't JSON serializable which is true, but is there a way to tell `redis-cache` to `await` instead of caching the coro itself? Or would that be a simple change to submit a PR for?

Thanks much!

**Comment by taylorhakes** [comment]
The library currently doesn’t support async. I would be happy to accept a PR for async with tests.

**Comment by mrisher** [comment]
Thanks for confirming. Can you give me a hint where we're start for the PR?
I will see if I can hack it... (with tests)

**Comment by taylorhakes** [comment]
Here is around the line that you would need to change:

https://github.com/taylorhakes/python-redis-cache/blob/master/redis_cache/__init__.py#L208


Here are some links on what needs to be done:

https://n8henrie.com/2021/11/decorator-to-memoize-sync-or-async-functions-in-python/

https://stackoverflow.com/questions/68410730/how-to-make-decorator-work-with-async-function
